### ISSUE TITLE
About your post about backdoor

### ISSUE THREAD

**Issue by khokm** [ekawahyu/ekawahyu.github.io#2]
https://github.com/ekawahyu/ekawahyu.github.io/blob/master/_posts/2015-05-08-hg8245-internet-backdoor-remote-access.md

Actually, if you try to connect from other network (not your LAN) to your WAN ip address - it will fail.

Try to check telnet port number (23) from outside using some port-cheker sites (for example https://portchecker.co). It will say that port is closed. That means, that router will accept telnet connection from outside only in case if peer ip is the WAN address of router itself.

This still isnt secure tho, because NAT is not firewall, and provider can have remote access to your router if he want to.

**Comment by ekawahyu** [comment]
I believe that's what I did, telnetting from WAN. I am not 100% sure because it was long time ago and I don't own this device anymore.
